### ISSUE TITLE
Excelent tool, a question tho

### ISSUE THREAD

**Issue by malloot** [liekki/wowapi#1]
Hey, how is the value of the mobs calculated? does it include the skinning for example?

Would be a lot more useful if the AH value of items is tracked as well by weekly Auctioneer scan

**Comment by liekki** [comment]
Hey,

You can see how the value is calculated here: https://github.com/liekki/wowapi/blob/master/scripts/calculateValues.js#L58

So basically it's just the direct sell value for each possible item in the loot table adjusted for drop chance, of course plus the average "wealth" that humanoids have, for example. 

It currently does not include the value from skinning but I think it would be fairly trivial to implement it. However, not everyone has skinning so it shouldn't be a default option.

As to the auction house values.. yeah, that's an interesting idea. I'm not familiar with Auctioneer's data structure, but I'm sure you could maintain an AH price for the items and use it, if available.

**Comment by malloot** [comment]
Does the loot table account for mobs not dropping loot?

I ask because i was trying to grind a mob that seemed good based on average value and spawns but turned out pretty disappointing because of a quite high amount of the mobs not dropping loot at all. The ones that did drop loot often dropped 2 good grays so the value of those was undeniably high, the average was quite low though.

**Comment by liekki** [comment]
As far as I know, mobs not dropping anything is just bad luck. If a mob has a loot table with a 50% chance to drop Silk Cloth and a 50% chance to drop a gray junk item, you'll get nothing 25% of the time.

Anyway, if those mobs dropped good grays ALL the time, I think the average value would be even higher. What mob was this btw?
